# Verificando indicadores regionalizados

In [1]:
import pandas as pd

In [2]:
df_inidcador = pd.read_csv('resultados/indicador.csv.gz')

In [3]:
df_inidcador.columns

Index(['Unnamed: 0', 'cd_indicador', 'nm_indicador', 'dc_formula_indicador',
       'dc_conceito_indicador', 'dc_interpretacao_indicador',
       'dc_nota_tecnica', 'in_visibilidade', 'cd_tipo_situacao',
       'dt_atualizacao', 'cd_operador', 'cd_tipo_unidade_medida', 'cd_fonte',
       'nm_completo_indicador', 'dc_periodicidade_indicador',
       'dc_unidade_territorial', 'dc_serie_historica', 'dc_tag_indicador',
       'dc_observacao_indicador', 'tx_fonte_indicador',
       'in_consideracao_regiao'],
      dtype='object')

In [6]:
df_inidcador

,Unnamed: 0,cd_indicador,nm_indicador,dc_formula_indicador,dc_conceito_indicador,dc_interpretacao_indicador,dc_nota_tecnica,in_visibilidade,cd_tipo_situacao,dt_atualizacao,...,cd_tipo_unidade_medida,cd_fonte,nm_completo_indicador,dc_periodicidade_indicador,dc_unidade_territorial,dc_serie_historica,dc_tag_indicador,dc_observacao_indicador,tx_fonte_indicador,in_consideracao_regiao
0,0,13.0,PIB per capita,"[{""caractere"":""PIB582"",""tipo"":""variavel""},{""ca...",NaN,NaN,NaN,False,3,2019-01-30 15:40:38.830537,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,1,7.0,TEste de exclusão,"[{""caractere"":""FdÔC882"",""tipo"":""variavel""},{""c...",NaN,NaN,NaN,True,3,2019-01-25 15:38:17.590074,...,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,2,1.0,Porcentagem da população com deficiência menta...,"[{""caractere"":""("",""tipo"":""agregador""},{""caract...",Porcentagem da população com deficiência menta...,SALVAR IXXXXXXX,"Na contagem da população com deficiência, foi ...",True,3,2019-01-24 10:37:49.389301,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,3,5.0,TEste de exclusão,"[{""caractere"":""FdÔC882"",""tipo"":""variavel""},{""c...",NaN,NaN,NaN,False,3,2019-01-25 13:40:50.882457,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
4,4,6.0,TEste de exclusão,"[{""caractere"":""FdÔC882"",""tipo"":""variavel""},{""c...",NaN,NaN,NaN,False,3,2019-01-25 15:36:10.068724,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
414,414,410.0,Proporção interna ao Distrito de empregos form...,"[{""caractere"":""("",""tipo"":""agregador""},{""caract...",Demonstra quais são as parcelas distribuídas p...,NaN,NaN,False,3,2020-06-02 11:23:57.142900,...,2,NaN,Percentual de empregos formais no setor de Ser...,Anual,Município,Inicio: 2002 - atualmente,NaN,NaN,Relação Anual de Informações Sociais (RAIS),False
415,415,91.0,Taxa de evasão escolar no Ensino Médio da rede...,"[{""caractere"":""("",""tipo"":""agregador""},{""caract...",NaN,NaN,NaN,False,1,2020-11-25 10:44:19.761688,...,2,NaN,Expressa o percentual de alunos matriculados n...,Anual,Município; Distrito; Subprefeitura,Início: 2016 - Atualmente\r\n,NaN,Lei Municipal nº 14.173/06\r\nO número de matr...,Censo Escolar do Ministério da Educação (MEC) ...,False
416,416,94.0,Taxa de repetência dos alunos no Ensino Fundam...,"[{""caractere"":""("",""tipo"":""agregador""},{""caract...",NaN,NaN,"O número de matrículas, contido na fórmula do ...",False,1,2020-11-25 10:46:39.846684,...,2,NaN,Expressa o percentual de alunos matriculados n...,Anual,Município; Distrito; Subprefeitura,Início: 2016 - atualmente,NaN,Lei nº 14.173/06\r\n,Censo do Ministério da Educação (MEC); Secreta...,False
417,417,96.0,Taxa de repetência dos alunos no Ensino Médio ...,"[{""caractere"":""("",""tipo"":""agregador""},{""caract...",NaN,NaN,"O número de matrículas, contido na fórmula do ...",False,1,2020-11-25 10:47:18.395534,...,2,NaN,Expressa o percentual de alunos matriculados n...,Anual,Município; Distrito; Subprefeitura,Início: 2008 - atualmente,NaN,Lei nº 14.173/06\r\n,Censo do Ministério da Educação (MEC); Secreta...,False
418,418,29.0,Taxa de Universalização da Educação Básica (%),"[{""caractere"":""("",""tipo"":""agregador""},{""caract...",Expressa se a população de determinada faixa e...,NaN,NaN,False,1,2020-11-25 10:47:53.319140,...,2,NaN,Percentual da população de 4 a 17 anos matricu...,Anual,Município; Distrito; Subprefeitura,Inicio: 2010 - atualmente,NaN,100% ou mais pode indicar que a cidade atrai p...,Fundação Sistema Estadual de Análise de Dados ...,False

In [30]:
df_inidcador.loc[~df_inidcador.in_consideracao_regiao, ['cd_indicador', 'nm_indicador']]

     cd_indicador                                       nm_indicador
31          189.0           Solicitações do 156 – Acessibilidade (%)
38          395.0  Número de atendimentos realizados pelos serviç...
40          396.0  Número de projetos em execução fomentados pelo...
41          409.0  Proporção interna ao Distrito de empregos form...
44          211.0  [ODS.08.01] PIB per capita a preços correntes ...
..            ...                                                ...
414         410.0  Proporção interna ao Distrito de empregos form...
415          91.0  Taxa de evasão escolar no Ensino Médio da rede...
416          94.0  Taxa de repetência dos alunos no Ensino Fundam...
417          96.0  Taxa de repetência dos alunos no Ensino Médio ...
418          29.0     Taxa de Universalização da Educação Básica (%)

[111 rows x 2 columns]

In [29]:
df_inidcador.loc[~df_inidcador.in_consideracao_regiao, ['cd_indicador', 'nm_indicador']].to_csv('resultados/indicadores_marcados_para_ignorar_regiao.csv')

In [17]:
df_inidcador.loc[df_inidcador.nm_indicador.str.contains('Alunos da rede municipal')].iloc[1].dc_formula_indicador

'[{"caractere":"(","tipo":"agregador"},{"caractere":"V0034","tipo":"variavel"},{"caractere":"/","tipo":"operador"},{"caractere":"V0009","tipo":"variavel"},{"caractere":")","tipo":"agregador"},{"caractere":"*","tipo":"operador"},{"caractere":"100","tipo":"constante"}]'

In [18]:
df_variavel = pd.read_csv('resultados/variavel.csv.gz')

In [31]:
df_variavel.loc[df_variavel.nm_resumido_variavel == 'V0034']

,Unnamed: 0,cd_variavel,nm_resumido_variavel,nm_completo_variavel,dt_atualizacao,cd_operador,cd_fonte,cd_tipo_situacao,nm_apelido_variavel,dc_periodo_atualizacao,in_variavel_basica,dc_unidade_variavel,dc_periodicidade_variavel,dc_unidade_territorial,dc_serie_historica,dc_nota_tecnica,dc_observacao_variavel,tx_fonte_variavel
122,122,73.0,V0034,Alunos da rede municipal de ensino da raça/cor...,2019-07-12 11:49:57.802175,184147,50.0,1,Alunos da rede municipal de ensino da raça/cor...,NaN,NaN,Matrícula,Anual,"Distrito, Subprefeitura, Município",início: 2016 - atualmente,NaN,NaN,"Ministério da Educação/Censo MEC, Secretaria ..."

In [24]:
df_variavel_resultado = pd.read_csv('resultados/variavel_resultado.csv.gz')

In [26]:
df_variavel_resultado.columns

Index(['Unnamed: 0', 'cd_sequencia_variavel_resultado', 'cd_periodo',
       'cd_variavel', 'cd_regiao', 'cd_tipo_situacao', 'cd_tipo_origem',
       'vl_variavel_resultado', 'dt_atualizacao', 'cd_do_operador'],
      dtype='object')

In [39]:
df_variavel_resultado[df_variavel_resultado.cd_variavel == 122].cd_regiao.value_counts()

196.0    4
162.0    4
185.0    4
190.0    4
167.0    4
        ..
161.0    4
116.0    4
140.0    4
19.0     4
6.0      4
Name: cd_regiao, Length: 129, dtype: int64

In [40]:
df_variavel = pd.read_csv('resultados/variavel.csv.gz')

In [47]:
df_variavel_resultado.cd_variavel.value_counts()

168.0    2709
290.0    2709
382.0    2709
31.0     2709
381.0    2709
         ...
453.0       1
348.0       1
434.0       1
410.0       1
408.0       1
Name: cd_variavel, Length: 418, dtype: int64

In [48]:
df_indicador = pd.read_csv('resultados/indicador.csv.gz')

In [49]:
df_indicador

,Unnamed: 0,cd_indicador,nm_indicador,dc_formula_indicador,dc_conceito_indicador,dc_interpretacao_indicador,dc_nota_tecnica,in_visibilidade,cd_tipo_situacao,dt_atualizacao,...,cd_tipo_unidade_medida,cd_fonte,nm_completo_indicador,dc_periodicidade_indicador,dc_unidade_territorial,dc_serie_historica,dc_tag_indicador,dc_observacao_indicador,tx_fonte_indicador,in_consideracao_regiao
0,0,13.0,PIB per capita,"[{""caractere"":""PIB582"",""tipo"":""variavel""},{""ca...",NaN,NaN,NaN,False,3,2019-01-30 15:40:38.830537,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,1,7.0,TEste de exclusão,"[{""caractere"":""FdÔC882"",""tipo"":""variavel""},{""c...",NaN,NaN,NaN,True,3,2019-01-25 15:38:17.590074,...,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,2,1.0,Porcentagem da população com deficiência menta...,"[{""caractere"":""("",""tipo"":""agregador""},{""caract...",Porcentagem da população com deficiência menta...,SALVAR IXXXXXXX,"Na contagem da população com deficiência, foi ...",True,3,2019-01-24 10:37:49.389301,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,3,5.0,TEste de exclusão,"[{""caractere"":""FdÔC882"",""tipo"":""variavel""},{""c...",NaN,NaN,NaN,False,3,2019-01-25 13:40:50.882457,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
4,4,6.0,TEste de exclusão,"[{""caractere"":""FdÔC882"",""tipo"":""variavel""},{""c...",NaN,NaN,NaN,False,3,2019-01-25 15:36:10.068724,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
414,414,410.0,Proporção interna ao Distrito de empregos form...,"[{""caractere"":""("",""tipo"":""agregador""},{""caract...",Demonstra quais são as parcelas distribuídas p...,NaN,NaN,False,3,2020-06-02 11:23:57.142900,...,2,NaN,Percentual de empregos formais no setor de Ser...,Anual,Município,Inicio: 2002 - atualmente,NaN,NaN,Relação Anual de Informações Sociais (RAIS),False
415,415,91.0,Taxa de evasão escolar no Ensino Médio da rede...,"[{""caractere"":""("",""tipo"":""agregador""},{""caract...",NaN,NaN,NaN,False,1,2020-11-25 10:44:19.761688,...,2,NaN,Expressa o percentual de alunos matriculados n...,Anual,Município; Distrito; Subprefeitura,Início: 2016 - Atualmente\r\n,NaN,Lei Municipal nº 14.173/06\r\nO número de matr...,Censo Escolar do Ministério da Educação (MEC) ...,False
416,416,94.0,Taxa de repetência dos alunos no Ensino Fundam...,"[{""caractere"":""("",""tipo"":""agregador""},{""caract...",NaN,NaN,"O número de matrículas, contido na fórmula do ...",False,1,2020-11-25 10:46:39.846684,...,2,NaN,Expressa o percentual de alunos matriculados n...,Anual,Município; Distrito; Subprefeitura,Início: 2016 - atualmente,NaN,Lei nº 14.173/06\r\n,Censo do Ministério da Educação (MEC); Secreta...,False
417,417,96.0,Taxa de repetência dos alunos no Ensino Médio ...,"[{""caractere"":""("",""tipo"":""agregador""},{""caract...",NaN,NaN,"O número de matrículas, contido na fórmula do ...",False,1,2020-11-25 10:47:18.395534,...,2,NaN,Expressa o percentual de alunos matriculados n...,Anual,Município; Distrito; Subprefeitura,Início: 2008 - atualmente,NaN,Lei nº 14.173/06\r\n,Censo do Ministério da Educação (MEC); Secreta...,False
418,418,29.0,Taxa de Universalização da Educação Básica (%),"[{""caractere"":""("",""tipo"":""agregador""},{""caract...",Expressa se a população de determinada faixa e...,NaN,NaN,False,1,2020-11-25 10:47:53.319140,...,2,NaN,Percentual da população de 4 a 17 anos matricu...,Anual,Município; Distrito; Subprefeitura,Inicio: 2010 - atualmente,NaN,100% ou mais pode indicar que a cidade atrai p...,Fundação Sistema Estadual de Análise de Dados ...,False

In [51]:
df_indicador.dc_formula_indicador[0]

'[{"caractere":"PIB582","tipo":"variavel"},{"caractere":"/","tipo":"operador"},{"caractere":"Pbp757","tipo":"variavel"}]'

In [52]:
import json

In [83]:
df_indicador.dc_formula_indicador.apply(json.loads)[16][0]

{'caractere': '(', 'tipo': 'agregador'}

In [149]:
df_indicador.dc_formula_indicador.apply(json.loads)

0      [{'caractere': 'PIB582', 'tipo': 'variavel'}, ...
1      [{'caractere': 'FdÔC882', 'tipo': 'variavel'},...
2      [{'caractere': '(', 'tipo': 'agregador'}, {'ca...
3      [{'caractere': 'FdÔC882', 'tipo': 'variavel'},...
4      [{'caractere': 'FdÔC882', 'tipo': 'variavel'},...
                             ...
414    [{'caractere': '(', 'tipo': 'agregador'}, {'ca...
415    [{'caractere': '(', 'tipo': 'agregador'}, {'ca...
416    [{'caractere': '(', 'tipo': 'agregador'}, {'ca...
417    [{'caractere': '(', 'tipo': 'agregador'}, {'ca...
418    [{'caractere': '(', 'tipo': 'agregador'}, {'ca...
Name: dc_formula_indicador, Length: 419, dtype: object

In [155]:
df_indicador.iloc[418].dc_formula_indicador

'[{"caractere":"(","tipo":"agregador"},{"caractere":"V0012","tipo":"variavel"},{"caractere":"/","tipo":"operador"},{"caractere":"V0011","tipo":"variavel"},{"caractere":")","tipo":"agregador"},{"caractere":"*","tipo":"operador"},{"caractere":"100","tipo":"constante"}]'

In [117]:
pd.concat([pd.DataFrame(pd.json_normalize(x)) for x in df_indicador.dc_formula_indicador.apply(json.loads)])

   caractere       tipo
0     PIB582   variavel
1          /   operador
2     Pbp757   variavel
0    FdÔC882   variavel
1          *   operador
..       ...        ...
2          /   operador
3      V0011   variavel
4          )  agregador
5          *   operador
6        100  constante

[1746 rows x 2 columns]

In [156]:
formulas = []

for i, r in df_indicador.iterrows():
#     formulas.append(pd.json_normalize(json.loads(r.dc_formula_indicador)))
    df_j = pd.json_normalize(json.loads(r.dc_formula_indicador))
    df_j['cd_indicador'] = r.cd_indicador
    formulas.append(df_j)

In [157]:
df_formulas = pd.concat(formulas)

In [163]:
df_formulas[df_formulas.cd_indicador == 418.0]

  caractere       tipo  cd_indicador
0         (  agregador         418.0
1     V0337   variavel         418.0
2         /   operador         418.0
3     V0338   variavel         418.0
4         )  agregador         418.0
5         *   operador         418.0
6       100  constante         418.0

In [142]:
# indicador --> Formula --> Variavel --> Variável_resultado

In [177]:
df_indicador_variavel_resultado = df_indicador.merge(df_formulas, how='left', on='cd_indicador')\
.merge(df_variavel, how='left', left_on='caractere', right_on='nm_resumido_variavel')\
.merge(df_variavel_resultado, how='left', on='cd_variavel')

In [183]:
df_indicador_variavel_resultado.columns

Index(['Unnamed: 0_x', 'cd_indicador', 'nm_indicador', 'dc_formula_indicador',
       'dc_conceito_indicador', 'dc_interpretacao_indicador',
       'dc_nota_tecnica_x', 'in_visibilidade', 'cd_tipo_situacao_x',
       'dt_atualizacao_x', 'cd_operador_x', 'cd_tipo_unidade_medida',
       'cd_fonte_x', 'nm_completo_indicador', 'dc_periodicidade_indicador',
       'dc_unidade_territorial_x', 'dc_serie_historica_x', 'dc_tag_indicador',
       'dc_observacao_indicador', 'tx_fonte_indicador',
       'in_consideracao_regiao', 'caractere', 'tipo', 'Unnamed: 0_y',
       'cd_variavel', 'nm_resumido_variavel', 'nm_completo_variavel',
       'dt_atualizacao_y', 'cd_operador_y', 'cd_fonte_y', 'cd_tipo_situacao_y',
       'nm_apelido_variavel', 'dc_periodo_atualizacao', 'in_variavel_basica',
       'dc_unidade_variavel', 'dc_periodicidade_variavel',
       'dc_unidade_territorial_y', 'dc_serie_historica_y', 'dc_nota_tecnica_y',
       'dc_observacao_variavel', 'tx_fonte_variavel', 'Unnamed: 0',
       'cd_sequencia_variavel_resultado', 'cd_periodo', 'cd_regiao',
       'cd_tipo_situacao', 'cd_tipo_origem', 'vl_variavel_resultado',
       'dt_atualizacao', 'cd_do_operador'],
      dtype='object')

In [208]:
df_indicador_variavel_resultado.loc[~df_indicador_variavel_resultado.in_consideracao_regiao, \
                                    ['cd_indicador',\
                                    'nm_indicador',\
                                    'cd_periodo',\
                                    'cd_regiao']].\
groupby(by=['cd_indicador']).\
agg({
    'nm_indicador':'first',
#     'cd_periodo':'count',
    'cd_regiao':'nunique'
})#.to_csv('resultados/indicadores_e_contagem_variavel_por_regiao.csv')

                                                   nm_indicador  cd_regiao
cd_indicador
27.0          Alunos da rede municipal de ensino do sexo fem...        129
28.0          Alunos da rede municipal de ensino do sexo mas...        129
29.0             Taxa de Universalização da Educação Básica (%)        129
31.0          Alunos por turma do ensino fundamental da rede...        129
37.0          [ODS.04.02] Taxa de Universalização da Educaçã...        129
...                                                         ...        ...
417.0         Proporção de empregos formais na Indústria de ...          2
418.0         Proporção de empregos formais na Construção Ci...          2
419.0         Proporção de empregos formais na Indústria da ...         97
420.0         Proporção de empregos formais na Construção Ci...         97
421.0         Casos reportados de abuso sexual no transporte...          1

[111 rows x 2 columns]

In [2]:
df_regioes = pd.read_csv('resultados/regiao.csv.gz')

In [3]:
df_regioes

,Unnamed: 0,cd_regiao,cd_regiao_macro,sg_regiao,nm_regiao,cd_nivel_regiao,dt_atualizacao,cd_operador,cd_tipo_situacao,sg_regiao_smul
0,0,24.0,NaN,IT,ITAIM PAULISTA,2,2019-04-08 18:33:36.486583,t010001,1,S24
1,1,25.0,NaN,MO,MOOCA,2,2019-04-08 18:34:23.811583,t010001,1,S25
2,2,29.0,NaN,VP,VILA PRUDENTE,2,2019-04-08 18:38:55.271583,t010001,1,S29
3,3,5.0,NaN,ST,SANTANA-TUCURUVI,2,2019-04-08 17:46:50.952583,t010001,1,S05
4,4,26.0,NaN,AF,ARICANDUVA-FORMOSA-CARRÃO,2,2019-04-08 18:47:13.920583,t010001,1,S26
...,...,...,...,...,...,...,...,...,...,...
125,125,167.0,NaN,RPE,Rio Pequeno,1,2019-04-08 20:04:50.325183,t010001,1,D67
126,126,168.0,NaN,SAC,Sacomã,1,2019-04-08 20:04:50.325183,t010001,1,D68
127,127,169.0,NaN,SCE,Santa Cecília,1,2019-04-08 20:04:50.325183,t010001,1,D69
128,128,170.0,NaN,SAN,Santana,1,2019-04-08 20:04:50.325183,t010001,1,D70
129,129,197.0,NaN,SP,Estado de São Paulo,9,2019-08-08 17:40:10.359852,184147,1,SP00

In [5]:
df_regioes.cd_nivel_regiao.value_counts()

1    96
2    32
8     1
9     1
Name: cd_nivel_regiao, dtype: int64